### ISSUE TITLE
Setup Bob with virtual windows desktop

### ISSUE THREAD

**Issue by florianm** [florianm/turtle-planning#11]
Florian to setup Bob to use virtual windows desktop guacamole.dpaw.wa.gov.au and use admin db frontend from there (will run faster with test db on aws-mssql-001)

**Comment by simonwoodman** [comment]
I've had a look at the form in the application that was causing
problems for Bob in the TEST environment. I've identified the issue
and come up with a fix for the problem, so it should run better
whether regardless of whether the database is local or remote.
----- Original Message -----
From: "florianm/turtle-planning" 
To:"florianm/turtle-planning" 
Cc:
Sent:Fri, 10 Apr 2015 07:38:39 -0700
Subject:[turtle-planning] Setup Bob with virtual windows desktop (#11)

```
Florian to setup Bob to use virtual windows desktop
```

guacamole.dpaw.wa.gov.au and use admin db frontend from there (will
run faster with test db on aws-mssql-001) 

```
—
```

Reply to this email directly or view it on GitHub [1].     

## Links:

[1] https://github.com/florianm/turtle-planning/issues/11
