### ISSUE TITLE
Document current issues

### ISSUE THREAD

**Issue by florianm** [florianm/turtle-planning#16]
Florian or bob to write down:
- data missing? 
- data corrupted?
- what's missing in data and nfunctionality?

**Comment by RyanDou** [comment]
From a user/data entry point of view: 
When I select the tagging team, activities, etc before going into the data entry wizard the front end no longer seems to remember my 'Activity' choices and includes them all.
Shows activities chosen: ![image](https://cloud.githubusercontent.com/assets/11881636/8998371/7f1aef18-375e-11e5-9c4b-54603c0b17db.png)
Shows the activities available: 
![image](https://cloud.githubusercontent.com/assets/11881636/8998377/9f3c06b0-375e-11e5-935a-7b04af85080e.png)

**Comment by simonwoodman** [comment]
We've made this change in the past year. The activities list is only accessible by having the top level password, so a user without this can not modify it. After discussions with Bob and Scott it was decided that there was no reason to not have all activities available in the drop down list. This can be easily changed back if required.

**Comment by RyanDou** [comment]
I had a chat to Scott about this an he is happy for it to be implemented in again. Obviously with the top level password still limiting access for the casual user. It just saves accidental entering of irrelevant activities and much easier selection of the intended activity especially given some datasheets have different phrasing to the database, so in a long list it can be quite hard finding the equivalent activity.
